import HouLean.OpenCL.Compiler
import HouLean.OpenCL.Basic
import HouLean.Data.Float

open HouLean OpenCL Math

namespace HouLean.OpenCL

variable {R} [FloatType R] (x y : R)


impl_by : acos x ==> acos(x)
--impl_by : acosh x ==> acosh(x)
--impl_by : acospi x ==> acospi(x)
impl_by : asin x ==> asin(x)
-- impl_by : asinh x ==> asinh(x)
-- impl_by : asinpi x =>> asin(x)
impl_by : atan x ==> atan(x)
impl_by : atan2 y x ==> atan2(y,x)
-- impl_by : atanh x ==> atanh(x)
-- impl_by : atanhpi x ==> atanhpi(x)
-- impl_by : cbrt x ==> cbrt(x)
impl_by : ceil x ==> ceil(x)
-- impl_by : copysign x y ==> copysign(x,y)
impl_by : cos x ==> cos(x)
impl_by : cosh x ==> cosh(x)
-- impl_by : cospi x ==> cospi(x)
-- impl_by : half_divide x y ==> half_divide(x,y)
-- impl_by : native_divide x y ==> native_divide(x,y)
-- impl_by : erfc x ==> erfc x
-- impl_by : erf x ==> erf(x)
impl_by : exp x ==> exp(x)
impl_by : exp2 x ==> exp2(x)
-- impl_by : exp10 x ==> exp10(x)
-- impl_by : expm1 x ==> expm1(x)
impl_by : abs x ==> fabs(x)
-- impl_by : fdim x y ==> fdim(x, y)
impl_by : floor x ==> floor(x)
-- impl_by : fma a b c ==> fma(a, b, c)
impl_by : max x y ==> fmax(x, y)
impl_by : min x y ==> fmin(x, y)
-- impl_by : fmod x y ==> fmod(x, y)
-- impl_by : fract x ==> fract(x, (float*)0)
-- impl_by : frexp x exp ==> frexp(x, exp)
-- impl_by : hypot x y ==> hypot(x, y)
-- impl_by : ilogb x ==> ilogb(x)
-- impl_by : ldexp x n ==> ldexp(x, n)
-- impl_by : lgamma x ==> lgamma(x)
-- impl_by : lgamma_r x signp ==> lgamma_r(x, signp)
impl_by : log x ==> log(x)
impl_by : log2 x ==> log2(x)
impl_by : log10 x ==> log10(x)
-- impl_by : log1p x ==> log1p(x)
-- impl_by : logb x ==> logb(x)
-- impl_by : mad a b c ==> mad(a, b, c)
-- impl_by : maxmag x y ==> maxmag(x, y)
-- impl_by : minmag x y ==> minmag(x, y)
-- impl_by : modf x iptr ==> modf(x, iptr)
-- impl_by : nan nancode ==> nan(nancode)
-- impl_by : nextafter x y ==> nextafter(x, y)
impl_by : x ^ y ==> pow(x, y)
-- impl_by (n : Int) : x ^ n ==> pown(x, y)
-- impl_by : powr x y ==> powr(x, y)
-- impl_by : half_recip x ==> half_recip(x)
-- impl_by : native_recip x ==> native_recip(x)
-- impl_by : remainder x y ==> remainder(x, y)
-- impl_by : remquo x y quo ==> remquo(x, y, quo)
-- impl_by : rint x ==> rint(x)
-- impl_by : rootn x y ==> rootn(x, y)
impl_by : round x ==> round(x)
-- impl_by : invsqrt x ==> rsqrt(x)
impl_by : sin x ==> sin(x)
-- impl_by : sincos x cosval ==> sincos(x, cosval)
impl_by : sinh x ==> sinh(x)
-- impl_by : sinpi x ==> sinpi(x)
impl_by : sqrt x ==> sqrt(x)
impl_by : tan x ==> tan(x)
impl_by : tanh x ==> tanh(x)
-- impl_by : tanpi x ==> tanpi(x)
-- impl_by : tgamma x ==> tgamma(x)
-- impl_by : trunc x ==> trunc(x)
